# Generated by Django 2.1.3 on 2018-11-29 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20181129_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favoured', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.Tag'),
        ),
    ]
