# Generated by Django 2.1.3 on 2018-12-11 20:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20181129_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=tinymce.models.HTMLField(default='asdsa'),
            preserve_default=False,
        ),
    ]
