# Generated by Django 2.1.3 on 2018-12-11 20:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20181211_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
